---
- name: check if the realm already exists
  command: radosgw-admin realm get --cluster={{ cluster }} --rgw-realm={{ rgw_realm }}
  register: realmcheck
  failed_when: False
  changed_when: False
  always_run: True

- name: check if the zonegroup already exists
  command: radosgw-admin zonegroup get --cluster={{ cluster }} --rgw-zonegroup={{ rgw_zonegroup }}
  register: zonegroupcheck
  failed_when: False
  changed_when: False
  always_run: True

- name: check if the zone already exists
  command: radosgw-admin zone get --cluster={{ cluster }} --rgw-zone={{ rgw_zone }}
  register: zonecheck
  failed_when: False
  changed_when: False
  always_run: True

- name: check if the system user already exists
  command: radosgw-admin user info --cluster={{ cluster }} --uid={{ rgw_zone_user }}
  register: usercheck
  failed_when: False
  changed_when: False
  always_run: True
